// Code generated by MockGen. DO NOT EDIT.
// Source: internal/integration/market/provider.go
//
// Generated by this command:
//
//	mockgen -source=internal/integration/market/provider.go -destination=internal/mock/market_provider_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	model "warden/internal/model"

	gomock "go.uber.org/mock/gomock"
)

// MockIMarketProvider is a mock of IMarketProvider interface.
type MockIMarketProvider struct {
	ctrl     *gomock.Controller
	recorder *MockIMarketProviderMockRecorder
}

// MockIMarketProviderMockRecorder is the mock recorder for MockIMarketProvider.
type MockIMarketProviderMockRecorder struct {
	mock *MockIMarketProvider
}

// NewMockIMarketProvider creates a new mock instance.
func NewMockIMarketProvider(ctrl *gomock.Controller) *MockIMarketProvider {
	mock := &MockIMarketProvider{ctrl: ctrl}
	mock.recorder = &MockIMarketProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIMarketProvider) EXPECT() *MockIMarketProviderMockRecorder {
	return m.recorder
}

// Indices mocks base method.
func (m *MockIMarketProvider) Indices(ctx context.Context) ([]model.IndexQuote, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Indices", ctx)
	ret0, _ := ret[0].([]model.IndexQuote)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Indices indicates an expected call of Indices.
func (mr *MockIMarketProviderMockRecorder) Indices(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Indices", reflect.TypeOf((*MockIMarketProvider)(nil).Indices), ctx)
}

// Kline mocks base method.
func (m *MockIMarketProvider) Kline(ctx context.Context, code, period, adjust string) ([]model.Kline, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Kline", ctx, code, period, adjust)
	ret0, _ := ret[0].([]model.Kline)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Kline indicates an expected call of Kline.
func (mr *MockIMarketProviderMockRecorder) Kline(ctx, code, period, adjust any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Kline", reflect.TypeOf((*MockIMarketProvider)(nil).Kline), ctx, code, period, adjust)
}

// Quotes mocks base method.
func (m *MockIMarketProvider) Quotes(ctx context.Context, codes []string) ([]model.StockQuote, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Quotes", ctx, codes)
	ret0, _ := ret[0].([]model.StockQuote)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Quotes indicates an expected call of Quotes.
func (mr *MockIMarketProviderMockRecorder) Quotes(ctx, codes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Quotes", reflect.TypeOf((*MockIMarketProvider)(nil).Quotes), ctx, codes)
}

// Search mocks base method.
func (m *MockIMarketProvider) Search(ctx context.Context, kw string) ([]model.StockBrief, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, kw)
	ret0, _ := ret[0].([]model.StockBrief)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockIMarketProviderMockRecorder) Search(ctx, kw any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockIMarketProvider)(nil).Search), ctx, kw)
}
