// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/market_quote.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/market_quote.go -destination=internal/mock/market_quote_repository_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	model "warden/internal/model"

	gomock "go.uber.org/mock/gomock"
)

// MockMarketQuoteRepository is a mock of MarketQuoteRepository interface.
type MockMarketQuoteRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMarketQuoteRepositoryMockRecorder
}

// MockMarketQuoteRepositoryMockRecorder is the mock recorder for MockMarketQuoteRepository.
type MockMarketQuoteRepositoryMockRecorder struct {
	mock *MockMarketQuoteRepository
}

// NewMockMarketQuoteRepository creates a new mock instance.
func NewMockMarketQuoteRepository(ctrl *gomock.Controller) *MockMarketQuoteRepository {
	mock := &MockMarketQuoteRepository{ctrl: ctrl}
	mock.recorder = &MockMarketQuoteRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMarketQuoteRepository) EXPECT() *MockMarketQuoteRepositoryMockRecorder {
	return m.recorder
}

// LatestIndexQuotes mocks base method.
func (m *MockMarketQuoteRepository) LatestIndexQuotes(ctx context.Context) ([]model.IndexQuote, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LatestIndexQuotes", ctx)
	ret0, _ := ret[0].([]model.IndexQuote)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LatestIndexQuotes indicates an expected call of LatestIndexQuotes.
func (mr *MockMarketQuoteRepositoryMockRecorder) LatestIndexQuotes(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LatestIndexQuotes", reflect.TypeOf((*MockMarketQuoteRepository)(nil).LatestIndexQuotes), ctx)
}

// LatestStockQuotes mocks base method.
func (m *MockMarketQuoteRepository) LatestStockQuotes(ctx context.Context, codes []string) ([]model.StockQuote, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LatestStockQuotes", ctx, codes)
	ret0, _ := ret[0].([]model.StockQuote)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LatestStockQuotes indicates an expected call of LatestStockQuotes.
func (mr *MockMarketQuoteRepositoryMockRecorder) LatestStockQuotes(ctx, codes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LatestStockQuotes", reflect.TypeOf((*MockMarketQuoteRepository)(nil).LatestStockQuotes), ctx, codes)
}

// SaveIndexQuotes mocks base method.
func (m *MockMarketQuoteRepository) SaveIndexQuotes(ctx context.Context, quotes []model.IndexQuote) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveIndexQuotes", ctx, quotes)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveIndexQuotes indicates an expected call of SaveIndexQuotes.
func (mr *MockMarketQuoteRepositoryMockRecorder) SaveIndexQuotes(ctx, quotes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveIndexQuotes", reflect.TypeOf((*MockMarketQuoteRepository)(nil).SaveIndexQuotes), ctx, quotes)
}

// SaveStockQuotes mocks base method.
func (m *MockMarketQuoteRepository) SaveStockQuotes(ctx context.Context, quotes []model.StockQuote) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveStockQuotes", ctx, quotes)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveStockQuotes indicates an expected call of SaveStockQuotes.
func (mr *MockMarketQuoteRepositoryMockRecorder) SaveStockQuotes(ctx, quotes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveStockQuotes", reflect.TypeOf((*MockMarketQuoteRepository)(nil).SaveStockQuotes), ctx, quotes)
}
