// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/market.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/market.go -destination=internal/mock/market_service_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	request "warden/internal/dto/request"
	model "warden/internal/model"

	gomock "go.uber.org/mock/gomock"
)

// MockQuoteCache is a mock of QuoteCache interface.
type MockQuoteCache struct {
	ctrl     *gomock.Controller
	recorder *MockQuoteCacheMockRecorder
}

// MockQuoteCacheMockRecorder is the mock recorder for MockQuoteCache.
type MockQuoteCacheMockRecorder struct {
	mock *MockQuoteCache
}

// NewMockQuoteCache creates a new mock instance.
func NewMockQuoteCache(ctrl *gomock.Controller) *MockQuoteCache {
	mock := &MockQuoteCache{ctrl: ctrl}
	mock.recorder = &MockQuoteCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuoteCache) EXPECT() *MockQuoteCacheMockRecorder {
	return m.recorder
}

// GetQuotes mocks base method.
func (m *MockQuoteCache) GetQuotes(ctx context.Context, codes []string) ([]model.StockQuote, []string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQuotes", ctx, codes)
	ret0, _ := ret[0].([]model.StockQuote)
	ret1, _ := ret[1].([]string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetQuotes indicates an expected call of GetQuotes.
func (mr *MockQuoteCacheMockRecorder) GetQuotes(ctx, codes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQuotes", reflect.TypeOf((*MockQuoteCache)(nil).GetQuotes), ctx, codes)
}

// SetQuotes mocks base method.
func (m *MockQuoteCache) SetQuotes(ctx context.Context, quotes []model.StockQuote) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetQuotes", ctx, quotes)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetQuotes indicates an expected call of SetQuotes.
func (mr *MockQuoteCacheMockRecorder) SetQuotes(ctx, quotes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetQuotes", reflect.TypeOf((*MockQuoteCache)(nil).SetQuotes), ctx, quotes)
}

// MockMarketService is a mock of MarketService interface.
type MockMarketService struct {
	ctrl     *gomock.Controller
	recorder *MockMarketServiceMockRecorder
}

// MockMarketServiceMockRecorder is the mock recorder for MockMarketService.
type MockMarketServiceMockRecorder struct {
	mock *MockMarketService
}

// NewMockMarketService creates a new mock instance.
func NewMockMarketService(ctrl *gomock.Controller) *MockMarketService {
	mock := &MockMarketService{ctrl: ctrl}
	mock.recorder = &MockMarketServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMarketService) EXPECT() *MockMarketServiceMockRecorder {
	return m.recorder
}

// AddWatchlist mocks base method.
func (m *MockMarketService) AddWatchlist(ctx context.Context, userID uint, req *request.AddWatchlistReq) (*model.WatchlistItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddWatchlist", ctx, userID, req)
	ret0, _ := ret[0].(*model.WatchlistItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddWatchlist indicates an expected call of AddWatchlist.
func (mr *MockMarketServiceMockRecorder) AddWatchlist(ctx, userID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddWatchlist", reflect.TypeOf((*MockMarketService)(nil).AddWatchlist), ctx, userID, req)
}

// DeleteWatchlist mocks base method.
func (m *MockMarketService) DeleteWatchlist(ctx context.Context, userID, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteWatchlist", ctx, userID, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteWatchlist indicates an expected call of DeleteWatchlist.
func (mr *MockMarketServiceMockRecorder) DeleteWatchlist(ctx, userID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteWatchlist", reflect.TypeOf((*MockMarketService)(nil).DeleteWatchlist), ctx, userID, id)
}

// Indices mocks base method.
func (m *MockMarketService) Indices(ctx context.Context) ([]model.IndexQuote, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Indices", ctx)
	ret0, _ := ret[0].([]model.IndexQuote)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Indices indicates an expected call of Indices.
func (mr *MockMarketServiceMockRecorder) Indices(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Indices", reflect.TypeOf((*MockMarketService)(nil).Indices), ctx)
}

// Kline mocks base method.
func (m *MockMarketService) Kline(ctx context.Context, code, period, adjust string) ([]model.Kline, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Kline", ctx, code, period, adjust)
	ret0, _ := ret[0].([]model.Kline)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Kline indicates an expected call of Kline.
func (mr *MockMarketServiceMockRecorder) Kline(ctx, code, period, adjust any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Kline", reflect.TypeOf((*MockMarketService)(nil).Kline), ctx, code, period, adjust)
}

// ListWatchlist mocks base method.
func (m *MockMarketService) ListWatchlist(ctx context.Context, userID uint) ([]model.WatchlistItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListWatchlist", ctx, userID)
	ret0, _ := ret[0].([]model.WatchlistItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListWatchlist indicates an expected call of ListWatchlist.
func (mr *MockMarketServiceMockRecorder) ListWatchlist(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListWatchlist", reflect.TypeOf((*MockMarketService)(nil).ListWatchlist), ctx, userID)
}

// Search mocks base method.
func (m *MockMarketService) Search(ctx context.Context, kw string) ([]model.StockBrief, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, kw)
	ret0, _ := ret[0].([]model.StockBrief)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockMarketServiceMockRecorder) Search(ctx, kw any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockMarketService)(nil).Search), ctx, kw)
}

// StockDetail mocks base method.
func (m *MockMarketService) StockDetail(ctx context.Context, code string) (*model.StockQuote, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StockDetail", ctx, code)
	ret0, _ := ret[0].(*model.StockQuote)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StockDetail indicates an expected call of StockDetail.
func (mr *MockMarketServiceMockRecorder) StockDetail(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StockDetail", reflect.TypeOf((*MockMarketService)(nil).StockDetail), ctx, code)
}

// WatchlistQuotes mocks base method.
func (m *MockMarketService) WatchlistQuotes(ctx context.Context, userID uint) ([]model.StockQuote, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WatchlistQuotes", ctx, userID)
	ret0, _ := ret[0].([]model.StockQuote)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WatchlistQuotes indicates an expected call of WatchlistQuotes.
func (mr *MockMarketServiceMockRecorder) WatchlistQuotes(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WatchlistQuotes", reflect.TypeOf((*MockMarketService)(nil).WatchlistQuotes), ctx, userID)
}
