// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/strategy.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/strategy.go -destination=internal/mock/strategy_repository_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	model "warden/internal/model"

	gomock "go.uber.org/mock/gomock"
)

// MockStrategyRepository is a mock of StrategyRepository interface.
type MockStrategyRepository struct {
	ctrl     *gomock.Controller
	recorder *MockStrategyRepositoryMockRecorder
}

// MockStrategyRepositoryMockRecorder is the mock recorder for MockStrategyRepository.
type MockStrategyRepositoryMockRecorder struct {
	mock *MockStrategyRepository
}

// NewMockStrategyRepository creates a new mock instance.
func NewMockStrategyRepository(ctrl *gomock.Controller) *MockStrategyRepository {
	mock := &MockStrategyRepository{ctrl: ctrl}
	mock.recorder = &MockStrategyRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStrategyRepository) EXPECT() *MockStrategyRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockStrategyRepository) Create(ctx context.Context, s *model.Strategy) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, s)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockStrategyRepositoryMockRecorder) Create(ctx, s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockStrategyRepository)(nil).Create), ctx, s)
}

// Delete mocks base method.
func (m *MockStrategyRepository) Delete(ctx context.Context, userID, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, userID, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockStrategyRepositoryMockRecorder) Delete(ctx, userID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockStrategyRepository)(nil).Delete), ctx, userID, id)
}

// GetByID mocks base method.
func (m *MockStrategyRepository) GetByID(ctx context.Context, userID, id uint) (*model.Strategy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, userID, id)
	ret0, _ := ret[0].(*model.Strategy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockStrategyRepositoryMockRecorder) GetByID(ctx, userID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockStrategyRepository)(nil).GetByID), ctx, userID, id)
}

// GetIndicator mocks base method.
func (m *MockStrategyRepository) GetIndicator(ctx context.Context, strategyID uint) (*model.StrategyIndicator, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIndicator", ctx, strategyID)
	ret0, _ := ret[0].(*model.StrategyIndicator)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIndicator indicates an expected call of GetIndicator.
func (mr *MockStrategyRepositoryMockRecorder) GetIndicator(ctx, strategyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIndicator", reflect.TypeOf((*MockStrategyRepository)(nil).GetIndicator), ctx, strategyID)
}

// GetSkill mocks base method.
func (m *MockStrategyRepository) GetSkill(ctx context.Context, strategyID uint) (*model.StrategySkill, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSkill", ctx, strategyID)
	ret0, _ := ret[0].(*model.StrategySkill)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSkill indicates an expected call of GetSkill.
func (mr *MockStrategyRepositoryMockRecorder) GetSkill(ctx, strategyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSkill", reflect.TypeOf((*MockStrategyRepository)(nil).GetSkill), ctx, strategyID)
}

// List mocks base method.
func (m *MockStrategyRepository) List(ctx context.Context, userID uint, kw, tag string) ([]model.Strategy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, userID, kw, tag)
	ret0, _ := ret[0].([]model.Strategy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockStrategyRepositoryMockRecorder) List(ctx, userID, kw, tag any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockStrategyRepository)(nil).List), ctx, userID, kw, tag)
}

// SaveIndicator mocks base method.
func (m *MockStrategyRepository) SaveIndicator(ctx context.Context, ind *model.StrategyIndicator) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveIndicator", ctx, ind)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveIndicator indicates an expected call of SaveIndicator.
func (mr *MockStrategyRepositoryMockRecorder) SaveIndicator(ctx, ind any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveIndicator", reflect.TypeOf((*MockStrategyRepository)(nil).SaveIndicator), ctx, ind)
}

// SaveSkill mocks base method.
func (m *MockStrategyRepository) SaveSkill(ctx context.Context, skill *model.StrategySkill) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveSkill", ctx, skill)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveSkill indicates an expected call of SaveSkill.
func (mr *MockStrategyRepositoryMockRecorder) SaveSkill(ctx, skill any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveSkill", reflect.TypeOf((*MockStrategyRepository)(nil).SaveSkill), ctx, skill)
}

// Update mocks base method.
func (m *MockStrategyRepository) Update(ctx context.Context, s *model.Strategy) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, s)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockStrategyRepositoryMockRecorder) Update(ctx, s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockStrategyRepository)(nil).Update), ctx, s)
}

// MockScreenResultRepository is a mock of ScreenResultRepository interface.
type MockScreenResultRepository struct {
	ctrl     *gomock.Controller
	recorder *MockScreenResultRepositoryMockRecorder
}

// MockScreenResultRepositoryMockRecorder is the mock recorder for MockScreenResultRepository.
type MockScreenResultRepositoryMockRecorder struct {
	mock *MockScreenResultRepository
}

// NewMockScreenResultRepository creates a new mock instance.
func NewMockScreenResultRepository(ctrl *gomock.Controller) *MockScreenResultRepository {
	mock := &MockScreenResultRepository{ctrl: ctrl}
	mock.recorder = &MockScreenResultRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScreenResultRepository) EXPECT() *MockScreenResultRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockScreenResultRepository) Create(ctx context.Context, r *model.StrategyScreenResult) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, r)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockScreenResultRepositoryMockRecorder) Create(ctx, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockScreenResultRepository)(nil).Create), ctx, r)
}

// GetByID mocks base method.
func (m *MockScreenResultRepository) GetByID(ctx context.Context, userID, strategyID, id uint) (*model.StrategyScreenResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, userID, strategyID, id)
	ret0, _ := ret[0].(*model.StrategyScreenResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockScreenResultRepositoryMockRecorder) GetByID(ctx, userID, strategyID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockScreenResultRepository)(nil).GetByID), ctx, userID, strategyID, id)
}

// Latest mocks base method.
func (m *MockScreenResultRepository) Latest(ctx context.Context, userID, strategyID uint) (*model.StrategyScreenResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Latest", ctx, userID, strategyID)
	ret0, _ := ret[0].(*model.StrategyScreenResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Latest indicates an expected call of Latest.
func (mr *MockScreenResultRepositoryMockRecorder) Latest(ctx, userID, strategyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Latest", reflect.TypeOf((*MockScreenResultRepository)(nil).Latest), ctx, userID, strategyID)
}

// Update mocks base method.
func (m *MockScreenResultRepository) Update(ctx context.Context, r *model.StrategyScreenResult) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, r)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockScreenResultRepositoryMockRecorder) Update(ctx, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockScreenResultRepository)(nil).Update), ctx, r)
}
