// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/strategy.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/strategy.go -destination=internal/mock/strategy_service_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	request "warden/internal/dto/request"
	response "warden/internal/dto/response"
	catalog "warden/internal/strategy/catalog"
	rule "warden/internal/strategy/rule"

	gomock "go.uber.org/mock/gomock"
)

// MockStrategyService is a mock of StrategyService interface.
type MockStrategyService struct {
	ctrl     *gomock.Controller
	recorder *MockStrategyServiceMockRecorder
}

// MockStrategyServiceMockRecorder is the mock recorder for MockStrategyService.
type MockStrategyServiceMockRecorder struct {
	mock *MockStrategyService
}

// NewMockStrategyService creates a new mock instance.
func NewMockStrategyService(ctrl *gomock.Controller) *MockStrategyService {
	mock := &MockStrategyService{ctrl: ctrl}
	mock.recorder = &MockStrategyServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStrategyService) EXPECT() *MockStrategyServiceMockRecorder {
	return m.recorder
}

// Catalog mocks base method.
func (m *MockStrategyService) Catalog() []catalog.Item {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Catalog")
	ret0, _ := ret[0].([]catalog.Item)
	return ret0
}

// Catalog indicates an expected call of Catalog.
func (mr *MockStrategyServiceMockRecorder) Catalog() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Catalog", reflect.TypeOf((*MockStrategyService)(nil).Catalog))
}

// Copy mocks base method.
func (m *MockStrategyService) Copy(ctx context.Context, userID, id uint) (*response.Strategy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Copy", ctx, userID, id)
	ret0, _ := ret[0].(*response.Strategy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Copy indicates an expected call of Copy.
func (mr *MockStrategyServiceMockRecorder) Copy(ctx, userID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Copy", reflect.TypeOf((*MockStrategyService)(nil).Copy), ctx, userID, id)
}

// Create mocks base method.
func (m *MockStrategyService) Create(ctx context.Context, userID uint, req *request.CreateStrategyReq) (*response.Strategy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, userID, req)
	ret0, _ := ret[0].(*response.Strategy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockStrategyServiceMockRecorder) Create(ctx, userID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockStrategyService)(nil).Create), ctx, userID, req)
}

// Delete mocks base method.
func (m *MockStrategyService) Delete(ctx context.Context, userID, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, userID, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockStrategyServiceMockRecorder) Delete(ctx, userID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockStrategyService)(nil).Delete), ctx, userID, id)
}

// Get mocks base method.
func (m *MockStrategyService) Get(ctx context.Context, userID, id uint) (*response.Strategy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, userID, id)
	ret0, _ := ret[0].(*response.Strategy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockStrategyServiceMockRecorder) Get(ctx, userID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockStrategyService)(nil).Get), ctx, userID, id)
}

// GetScreenResult mocks base method.
func (m *MockStrategyService) GetScreenResult(ctx context.Context, userID, strategyID, taskID uint) (*response.ScreenResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetScreenResult", ctx, userID, strategyID, taskID)
	ret0, _ := ret[0].(*response.ScreenResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetScreenResult indicates an expected call of GetScreenResult.
func (mr *MockStrategyServiceMockRecorder) GetScreenResult(ctx, userID, strategyID, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetScreenResult", reflect.TypeOf((*MockStrategyService)(nil).GetScreenResult), ctx, userID, strategyID, taskID)
}

// GetSkill mocks base method.
func (m *MockStrategyService) GetSkill(ctx context.Context, userID, id uint) (string, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSkill", ctx, userID, id)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetSkill indicates an expected call of GetSkill.
func (mr *MockStrategyServiceMockRecorder) GetSkill(ctx, userID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSkill", reflect.TypeOf((*MockStrategyService)(nil).GetSkill), ctx, userID, id)
}

// LatestScreenResult mocks base method.
func (m *MockStrategyService) LatestScreenResult(ctx context.Context, userID, strategyID uint) (*response.ScreenResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LatestScreenResult", ctx, userID, strategyID)
	ret0, _ := ret[0].(*response.ScreenResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LatestScreenResult indicates an expected call of LatestScreenResult.
func (mr *MockStrategyServiceMockRecorder) LatestScreenResult(ctx, userID, strategyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LatestScreenResult", reflect.TypeOf((*MockStrategyService)(nil).LatestScreenResult), ctx, userID, strategyID)
}

// List mocks base method.
func (m *MockStrategyService) List(ctx context.Context, userID uint, kw, tag string) ([]response.Strategy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, userID, kw, tag)
	ret0, _ := ret[0].([]response.Strategy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockStrategyServiceMockRecorder) List(ctx, userID, kw, tag any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockStrategyService)(nil).List), ctx, userID, kw, tag)
}

// PreviewScreen mocks base method.
func (m *MockStrategyService) PreviewScreen(ctx context.Context, userID uint, req *request.PreviewScreenReq) (*response.ScreenResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PreviewScreen", ctx, userID, req)
	ret0, _ := ret[0].(*response.ScreenResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PreviewScreen indicates an expected call of PreviewScreen.
func (mr *MockStrategyServiceMockRecorder) PreviewScreen(ctx, userID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PreviewScreen", reflect.TypeOf((*MockStrategyService)(nil).PreviewScreen), ctx, userID, req)
}

// RunScreen mocks base method.
func (m *MockStrategyService) RunScreen(ctx context.Context, userID, strategyID uint, req *request.ScreenReq) (uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunScreen", ctx, userID, strategyID, req)
	ret0, _ := ret[0].(uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RunScreen indicates an expected call of RunScreen.
func (mr *MockStrategyServiceMockRecorder) RunScreen(ctx, userID, strategyID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunScreen", reflect.TypeOf((*MockStrategyService)(nil).RunScreen), ctx, userID, strategyID, req)
}

// SaveSkill mocks base method.
func (m *MockStrategyService) SaveSkill(ctx context.Context, userID, id uint, content string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveSkill", ctx, userID, id, content)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveSkill indicates an expected call of SaveSkill.
func (mr *MockStrategyServiceMockRecorder) SaveSkill(ctx, userID, id, content any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveSkill", reflect.TypeOf((*MockStrategyService)(nil).SaveSkill), ctx, userID, id, content)
}

// Templates mocks base method.
func (m *MockStrategyService) Templates() []catalog.Template {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Templates")
	ret0, _ := ret[0].([]catalog.Template)
	return ret0
}

// Templates indicates an expected call of Templates.
func (mr *MockStrategyServiceMockRecorder) Templates() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Templates", reflect.TypeOf((*MockStrategyService)(nil).Templates))
}

// Update mocks base method.
func (m *MockStrategyService) Update(ctx context.Context, userID, id uint, req *request.UpdateStrategyReq) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, userID, id, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockStrategyServiceMockRecorder) Update(ctx, userID, id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockStrategyService)(nil).Update), ctx, userID, id, req)
}

// UpdateIndicators mocks base method.
func (m *MockStrategyService) UpdateIndicators(ctx context.Context, userID, id uint, group *rule.RuleGroup) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateIndicators", ctx, userID, id, group)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateIndicators indicates an expected call of UpdateIndicators.
func (mr *MockStrategyServiceMockRecorder) UpdateIndicators(ctx, userID, id, group any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateIndicators", reflect.TypeOf((*MockStrategyService)(nil).UpdateIndicators), ctx, userID, id, group)
}
