// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/watchlist.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/watchlist.go -destination=internal/mock/watchlist_repository_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	model "warden/internal/model"

	gomock "go.uber.org/mock/gomock"
)

// MockWatchlistRepository is a mock of WatchlistRepository interface.
type MockWatchlistRepository struct {
	ctrl     *gomock.Controller
	recorder *MockWatchlistRepositoryMockRecorder
}

// MockWatchlistRepositoryMockRecorder is the mock recorder for MockWatchlistRepository.
type MockWatchlistRepositoryMockRecorder struct {
	mock *MockWatchlistRepository
}

// NewMockWatchlistRepository creates a new mock instance.
func NewMockWatchlistRepository(ctrl *gomock.Controller) *MockWatchlistRepository {
	mock := &MockWatchlistRepository{ctrl: ctrl}
	mock.recorder = &MockWatchlistRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWatchlistRepository) EXPECT() *MockWatchlistRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockWatchlistRepository) Create(ctx context.Context, item *model.WatchlistItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, item)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockWatchlistRepositoryMockRecorder) Create(ctx, item any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockWatchlistRepository)(nil).Create), ctx, item)
}

// Delete mocks base method.
func (m *MockWatchlistRepository) Delete(ctx context.Context, userID, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, userID, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockWatchlistRepositoryMockRecorder) Delete(ctx, userID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockWatchlistRepository)(nil).Delete), ctx, userID, id)
}

// ExistsByCode mocks base method.
func (m *MockWatchlistRepository) ExistsByCode(ctx context.Context, userID uint, code string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsByCode", ctx, userID, code)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsByCode indicates an expected call of ExistsByCode.
func (mr *MockWatchlistRepositoryMockRecorder) ExistsByCode(ctx, userID, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsByCode", reflect.TypeOf((*MockWatchlistRepository)(nil).ExistsByCode), ctx, userID, code)
}

// List mocks base method.
func (m *MockWatchlistRepository) List(ctx context.Context, userID uint) ([]model.WatchlistItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, userID)
	ret0, _ := ret[0].([]model.WatchlistItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockWatchlistRepositoryMockRecorder) List(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockWatchlistRepository)(nil).List), ctx, userID)
}
